export { default as Homepage } from './Homepage'
export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'
export { default as ForgotPassword } from './auth/ForgotPassword'
export { default as ChangePassword } from './auth/ChangePassword'